repositories:
  - name: prometheus
    url: https://prometheus-community.github.io/helm-charts

releases:
  - name: prometheus
    namespace: monitoring
    createNamespace: true
    chart: prometheus/prometheus
    version: 25.17.0
    values:
      - alertmanager:
          enabled: true
        pushgateway:
          enabled: true
        server:
          service:
            type: NodePort
